<?php
$sozler = array(
  "Odaklanmak, 1000 iyi fikre hayır diyebilmektir.",
  "Kod yalan soylemez, yorumlar bazen soyler.",
  "Tasarım, nasıl başarısız olacağınızı seçmektir.",
  "Programcılar, geleceği düşündükleri için sürekli olarak işleri gereğinden fazla karmaşıklaştırmaktadırlar. Geleceği boşverin. Bugün için programlayın.",
  "İnsanlar, yazılımın ürün olmadığını, ürün üretmek için kullanıldığını anlayacaklar.",
  "Kod, espiri gibidir. Açıklamak zorundaysanız kotüdür.",
  "Kotü yonetim yazılım maliyetini diğer tüm faktorlerden daha hızlı arttırır.",
  "Servislerinizi birbirinden bağımsız olarak ayağa kaldıramıyorsanız mikroservis değillerdir.",
  "Basitlik, güvenilirlik için onkoşuldur.",
  "Kodunuzda NE yerine NEDEN'e odaklanmak sizi daha iyi bir geliştirici yapar.",
  "Kullanıcıları, sistemin zaten bildiği bir bilgiyi vermeye zorlamayın.",
  "Konuşmak bedava, bana kodu göster!",
  "Ben sadece icat ederim. Sonra insanların gelip icadıma ihtiyaç duymasını beklerim.",
  "Eğer fikrinizi yazıya dokemiyorsanız, onu kodlayamazsınız.",
  "İlerlemenin sırrı başlamaktır.",
  "Eğer gerçekler teorinize uymuyorsa gerçekliği değiştirin.",
  "Merak duygusunun zorunlu eğitimden sağ çıkması mucize.",
  "Aynı şeyi sürekli tekrarlayıp farklı sonuç beklemek deliliktir.",
  "Asla yanlış yapmamış insan, yeni hiç birşey denememiştir.",
  "Mantık sizi A noktasından B noktasına gotürür. Hayal gücü her yere.",
  "Hızlı, İyi, Ucuz. Sadece ikisini seçebilirsin.",
  "Mücadele yoksa ilerleme de yoktur.",
  "Bir projeyi daha hızlı bitirmenin en iyi yolu, erkenden başlamaktır.",
  "En iyi performans arttırımı, çalışmayan durumdan çalışır duruma getirmektir.",
  "Tüm büyük programlama felaketleri çok fazla fikri alıp tek bir yere koymaktan kaynaklanmıştır.",
  "Daha az kod yazmak, esnek kalmanın güzel bir yoludur.",
  "Performansın anahtarı zarafettir. Binlerce ozel durum gerçekleştirimi değildir.",
  "Neden hiçbir zaman DOĞRU yapmak için vaktimiz yok da, YENİDEN yapmak için vaktimiz var?",
  "Üretken bir programcının işe alınabilir olmasını beklemek, ilk bulunan programcının üretken olmasını beklemekten iyidir.",
  "Tasarımda mükemmellik, ekleyecek bir şey kalmadığında değil, çıkaracak bir şey kalmadığında yakalanır.",
  "Gizemli bir cinayetin sırlarını çozmek iyidir. Fakat kodun sırlarını çozmek zorunda kalmamalısınız. Kodun kolaylıkla anlaşılabilir olması gerekir.",
  "Yazılımcı; kahveyi koda çeviren organizma.",
  "Bazen Pazartesi günü tüm gün yatmak, haftanın kalanını Pazartesi yazılan kodu debug etmeye harcamaktan iyidir.",
  "Gereksinim veya tasarım olmadan programlama, boş bir dosyaya bug eklemekten başka bir şey değildir.",
  "Acı çekmeden oğrenemeyiz.",
  "Mükemmel fikirleri çalmak konusunda her zaman yüzsüz davrandık.",
  "Ancak ikisi de donmuşsa suda yürümek ve şartnameden yazılım geliştirmek kolaydır.",
  "Debug sırasında, acemiler hata giderici kod eklerler; uzmanlar ise kusurlu olan kodu çıkarırlar.",
  "Programlamadaki ilerleyişi yazılan kod satırı sayısıyla olçmek, uçak inşasındaki ilerleyişi ağırlıkla olçmeye benzer.",
  "İyi bir yazılımcı, tek yon bir yoldan karşıya geçerken iki yone de bakandır.",
  "Yazılım, yapmasını soylediğiniz işi yapar, yapmasını istediğinizi değil.",
  "Beta Latince'de \"Hala çalışmıyor\" demektir.",
  "Önce meseleyi çozün. Sonra kodu yazın.",
  "Benim makinemde çalışıyor.",
  "İnternetten bulunan kodu canlıdaki koda yapıştırmak, yolda bulunan sakızı çiğnemek gibidir.",
  "Bilgi güçtür.",
  "Okulumun eğitimimi engellemesine asla izin vermedim.",
  "Sorunun kaynağını düzeltin, semptomunu değil.",
);
$sozler_keys = array_rand($sozler, 1);
$sozler = $sozler[$sozler_keys];
echo $sozler;
?>
